### ISSUE TITLE
在windows下vs2017 php7.2.12 编译不过去

### ISSUE THREAD

**Issue by eecoor** [wwccss/phpsciter_old#1]
ext\phpsciter\include\sciter-x-api.h(263): error C2143: 语法错误: 缺少“)”(在“*”的前面) (编译源文件 main\internal_functions.c)
ext\phpsciter\include\sciter-x-api.h(263): error C2081: “SCITER_X_MSG”: 形参表中的名称非法 (编译源文件 main\internal_functions.c)
ext\phpsciter\include\sciter-x-api.h(263): error C2143: 语法错误: 缺少“;”(在“*”的前面) (编译源文件 main\internal_functions.c)
ext\phpsciter\include\sciter-x-api.h(263): error C2059: 语法错误:“*” (编译源文件 main\internal_functions.c)
ext\phpsciter\include\sciter-x-api.h(263): error C2059: 语法错误:“)” (编译源文件 main\internal_functions.c)
ext\phpsciter\include\sciter-x-api.h(265): error C2059: 语法错误:“}” (编译源文件 main\internal_functions.c)
ext\phpsciter\include\sciter-x-api.h(267): error C2143: 语法错误: 缺少“{”(在“*”的前面) (编译源文件 main\internal_functions.c)
ext\phpsciter\include\sciter-x-api.h(297): error C2143: 语法错误: 缺少“{”(在“*”的前面) (编译源文件 main\internal_functions.c)
ext\phpsciter\include\sciter-x-api.h(297): error C2143: 语法错误: 缺少“)”(在“*”的前面) (编译源文件 main\internal_functions.c)
ext\phpsciter\include\sciter-x-api.h(297): error C2059: 语法错误:“)” (编译源文件 main\internal_functions.c)
ext\phpsciter\include\sciter-x-api.h(298): error C2143: 语法错误: 缺少“;”(在“{”的前面) (编译源文件 main\internal_functions.c)
ext\phpsciter\include\sciter-x-api.h(298): error C2449: 在文件范围内找到“{”(是否缺少函数头?) (编译源文件 main\internal_functions.c)
ext\phpsciter\include\sciter-x-api.h(327): error C2059: 语法错误:“}” (编译源文件 main\internal_functions.c)
……

是我配置的不对吗？

**Comment by eecoor** [comment]
\vc15\x86\php-7.2.12-src
32位的版本

**Comment by easysoft** [comment]
收到，已经转给Neeke了。可能需要花点时间。

**Comment by Neeke** [comment]
https://ci.appveyor.com/project/Neeke/phpsciter/builds/27036552

仅支持zts
