### ISSUE TITLE
Bad idea:

### ISSUE THREAD

**Issue by c-smile** [wwccss/phpsciter_old#2]
> Windows: simply copying bin\64\sciter.dll to c:\windows\system32 is just enough

That is extremely bad idea to be honest.

sciter.dll shall be placed into folder where the exeuctable resides.  
And so each application will be able to use sciter.dll it was designed and tested for.

Alternatively you shold find some other way placing and loading sciter.dll from folder where your PHP files of the project reside. sciter.dll is a part of your application but not the whole OS.

**Comment by easysoft** [comment]
Thank you for your advice. We'll correct it.
